# Generated by Django 5.2.10 on 2026-01-10 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependencies', '0005_project_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('layer_type', models.CharField(choices=[('freeform', 'Freeform'), ('bounded_context', 'Bounded Context'), ('team', 'Team'), ('application', 'Application'), ('imported', 'Imported')], default='freeform', max_length=50)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order within vision')),
                ('is_imported', models.BooleanField(default=False)),
                ('source_identifier', models.CharField(blank=True, default='', help_text='External source ID (e.g., GitLab group ID)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('position_x', models.FloatField(blank=True, null=True)),
                ('position_y', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent group for hierarchical grouping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='vision.group')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='vision.layer')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('layer', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('shared', 'Shared'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('snapshot_data', models.JSONField(blank=True, help_text='Frozen state for sharing', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent vision for branching', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='vision.vision')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_type', models.CharField(choices=[('existence', 'Existence'), ('containment', 'Containment'), ('exclusion', 'Exclusion'), ('cardinality', 'Cardinality')], max_length=20)),
                ('natural_language', models.TextField(help_text="Human-readable statement, e.g., 'All payment APIs must be in the Payment domain'")),
                ('formal_expression', models.JSONField(blank=True, help_text='Machine-evaluable expression, e.g., {"type": "containment", "subject": "PaymentAPIs", "container": "PaymentDomain"}', null=True)),
                ('status', models.CharField(choices=[('informal', 'Informal'), ('semi_formal', 'Semi-Formal'), ('formal', 'Formal')], default='informal', max_length=20)),
                ('is_satisfied', models.BooleanField(help_text='Evaluation result (null = not evaluated)', null=True)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='vision.vision')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='layer',
            name='vision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='vision.vision'),
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('explicit', 'Explicit'), ('inferred', 'Inferred'), ('imported', 'Imported')], default='explicit', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='vision.group')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_group_memberships', to='dependencies.project')),
            ],
            options={
                'ordering': ['project__name'],
                'unique_together': {('group', 'project')},
            },
        ),
        migrations.CreateModel(
            name='LayerNodePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_positions', to='vision.layer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_layer_positions', to='dependencies.project')),
            ],
            options={
                'unique_together': {('layer', 'project')},
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('definition_type', models.CharField(choices=[('informal', 'Informal'), ('tag_expression', 'Tag Expression'), ('explicit_list', 'Explicit List')], default='informal', max_length=20)),
                ('tag_expression', models.JSONField(blank=True, help_text='Tag expression, e.g., {"and": ["payment", "api"]}', null=True)),
                ('explicit_members', models.JSONField(default=list, help_text='List of project keys for explicit_list type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vision', models.ForeignKey(blank=True, help_text='Vision scope (null = global reference)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='vision.vision')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'vision')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together={('vision', 'key')},
        ),
    ]
