# Generated by Django 5.2.10 on 2026-01-11 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('layout_data', models.JSONField(default=dict, help_text='Snapshot of layers, groups, and positions for this version')),
                ('is_active', models.BooleanField(default=False, help_text='Currently active version (for display purposes)')),
                ('order', models.IntegerField(default=0, help_text='Tab order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='vision.vision')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('vision', 'name')},
            },
        ),
    ]
