# Generated by Django 5.2.10 on 2026-03-23 14:13

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_projects', models.IntegerField(default=0)),
                ('total_sccs', models.IntegerField(default=0)),
                ('total_clusters', models.IntegerField(default=0)),
                ('proposals_generated', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('component_type', models.CharField(choices=[('java', 'Java/Maven'), ('npm', 'NPM Package'), ('pypi', 'Python Package'), ('nuget', 'NuGet Package'), ('service', 'Service'), ('other', 'Other')], default='java', max_length=20)),
                ('maven_group_id', models.CharField(blank=True, db_column='group_id', default='', max_length=255)),
                ('artifact_id', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.CharField(blank=True, default='', max_length=100)),
                ('internal', models.BooleanField(default=True, help_text='True for internal components, False for external packages')),
                ('status', models.CharField(choices=[('active', 'Active'), ('stale', 'Stale'), ('dormant', 'Dormant'), ('not_analyzed', 'Not Analyzed'), ('orphan', 'Orphan')], default='not_analyzed', max_length=20)),
                ('position_x', models.FloatField(blank=True, null=True)),
                ('position_y', models.FloatField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LayerDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level', models.IntegerField(help_text='Lower numbers = lower layers (e.g., 0=infrastructure, 1=domain, 2=application)')),
                ('description', models.TextField(blank=True, default='')),
                ('pattern', models.CharField(blank=True, default='', help_text="Regex pattern to auto-assign projects (e.g., '^infra:.*')", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DependencyGraph',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dependencies.component')),
            ],
            bases=('dependencies.component',),
        ),
        migrations.CreateModel(
            name='CheckmarxProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkmarx_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkmarx_projects', to='dependencies.component')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GitProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitlab_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('path_with_namespace', models.CharField(max_length=512, unique=True)),
                ('namespace', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('web_url', models.URLField(blank=True, default='', max_length=512)),
                ('default_branch', models.CharField(default='main', max_length=255)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='git_projects', to='dependencies.component')),
            ],
            options={
                'ordering': ['path_with_namespace'],
            },
        ),
        migrations.CreateModel(
            name='LayerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_assigned', models.BooleanField(default=False, help_text='True if assigned automatically via pattern matching')),
                ('assigned_at', models.DateTimeField(auto_now=True)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layer_assignment', to='dependencies.component')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dependencies.layerdefinition')),
            ],
            options={
                'ordering': ['layer__level', 'component__name'],
            },
        ),
        migrations.CreateModel(
            name='LayerViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_violations', to='dependencies.analysisrun')),
                ('source_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_violations', to='dependencies.component')),
                ('source_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dependencies.layerdefinition')),
                ('target_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_violations', to='dependencies.component')),
                ('target_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dependencies.layerdefinition')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('position_x', models.FloatField(blank=True, null=True)),
                ('position_y', models.FloatField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dependencies.nodegroup')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='component',
            name='group',
            field=models.ForeignKey(blank=True, db_column='node_group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='dependencies.nodegroup'),
        ),
        migrations.CreateModel(
            name='NodeMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_in', models.IntegerField(default=0, help_text='Number of incoming dependencies')),
                ('fan_out', models.IntegerField(default=0, help_text='Number of outgoing dependencies')),
                ('coupling_score', models.FloatField(default=0.0)),
                ('afferent_coupling', models.IntegerField(default=0, help_text='Ca - incoming dependencies')),
                ('efferent_coupling', models.IntegerField(default=0, help_text='Ce - outgoing dependencies')),
                ('instability', models.FloatField(default=0.0, help_text='I = Ce / (Ca + Ce), 0=stable, 1=unstable')),
                ('degree_centrality', models.FloatField(default=0.0)),
                ('betweenness_centrality', models.FloatField(default=0.0)),
                ('topological_order', models.IntegerField(blank=True, help_text='Position in topological ordering (if DAG)', null=True)),
                ('layer_depth', models.IntegerField(blank=True, help_text='Longest path from any root node', null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('analysis_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_metrics', to='dependencies.analysisrun')),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dependencies.component')),
            ],
            options={
                'verbose_name_plural': 'Node metrics',
                'ordering': ['-instability', '-coupling_score'],
            },
        ),
        migrations.CreateModel(
            name='RefactoringProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.CharField(max_length=20, unique=True)),
                ('proposal_type', models.CharField(choices=[('cycle_break', 'Cycle Breaking'), ('service_extraction', 'Service Extraction'), ('api_stabilization', 'API Stabilization'), ('boundary_redefinition', 'Boundary Redefinition')], max_length=50)),
                ('scope', models.JSONField(default=list)),
                ('impact', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('risk', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('summary', models.TextField()),
                ('root_cause', models.TextField(blank=True, default='')),
                ('steps', models.JSONField(default=list)),
                ('expected_improvement', models.TextField(blank=True, default='')),
                ('scc_size_before', models.IntegerField(blank=True, null=True)),
                ('fan_in_before', models.FloatField(blank=True, null=True)),
                ('fan_out_before', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='proposed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='dependencies.analysisrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SonarProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sonar_key', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('qualifier', models.CharField(default='TRK', max_length=10)),
                ('visibility', models.CharField(default='public', max_length=20)),
                ('last_analysis', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sonar_projects', to='dependencies.component')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('shared', 'Shared'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('snapshot_data', models.JSONField(blank=True, help_text='Frozen state for sharing', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent vision for branching', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='dependencies.vision')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', help_text='Optional description or rationale')),
                ('statement_type', models.CharField(blank=True, choices=[('existence', 'Existence'), ('containment', 'Containment'), ('exclusion', 'Exclusion'), ('cardinality', 'Cardinality'), ('coverage', 'Coverage'), ('correspondence', 'Correspondence'), ('refinement', 'Refinement')], max_length=20, null=True)),
                ('natural_language', models.TextField(help_text='Human-readable statement with $$$ref$$$ tokens')),
                ('formal_expression', models.JSONField(blank=True, help_text='Machine-evaluable expression', null=True)),
                ('status', models.CharField(choices=[('informal', 'Informal'), ('semi_formal', 'Semi-Formal'), ('formal', 'Formal')], default='informal', max_length=20)),
                ('is_satisfied', models.BooleanField(help_text='null = not evaluated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='dependencies.vision')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('definition_type', models.CharField(choices=[('informal', 'Informal'), ('tag_expression', 'Tag Expression'), ('explicit_list', 'Explicit List'), ('layer', 'Layer')], default='informal', max_length=20)),
                ('tag_expression', models.JSONField(blank=True, help_text='e.g., {"and": ["payment", "api"]}', null=True)),
                ('explicit_members', models.JSONField(default=list, help_text='List of project keys')),
                ('layer_id', models.IntegerField(blank=True, help_text='ID of referenced layer (for layer definition type)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='dependencies.vision')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='compile', max_length=50)),
                ('weight', models.IntegerField(default=1)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='dependencies.component')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='dependencies.component')),
            ],
            options={
                'ordering': ['source__name', 'target__name'],
                'unique_together': {('source', 'target', 'scope')},
            },
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['maven_group_id', 'artifact_id'], name='dependencies_co_maven_g_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reference',
            unique_together={('name', 'vision')},
        ),
    ]
