# Generated by Django 5.2.10 on 2026-01-09 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('qualifier', models.CharField(default='TRK', max_length=10)),
                ('visibility', models.CharField(default='public', max_length=20)),
                ('last_analysis', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='compile', max_length=50)),
                ('weight', models.IntegerField(default=1)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='dependencies.project')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='dependencies.project')),
            ],
            options={
                'ordering': ['source__name', 'target__name'],
                'unique_together': {('source', 'target', 'scope')},
            },
        ),
    ]
