# Generated by Django 5.2.10 on 2026-01-09 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencies', '0002_nodegroup_project_position_x_project_position_y_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_projects', models.IntegerField(default=0)),
                ('total_sccs', models.IntegerField(default=0)),
                ('total_clusters', models.IntegerField(default=0)),
                ('proposals_generated', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RefactoringProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.CharField(max_length=20, unique=True)),
                ('proposal_type', models.CharField(choices=[('cycle_break', 'Cycle Breaking'), ('service_extraction', 'Service Extraction'), ('api_stabilization', 'API Stabilization'), ('boundary_redefinition', 'Boundary Redefinition')], max_length=50)),
                ('scope', models.JSONField(default=list)),
                ('impact', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('risk', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('summary', models.TextField()),
                ('root_cause', models.TextField(blank=True, default='')),
                ('steps', models.JSONField(default=list)),
                ('expected_improvement', models.TextField(blank=True, default='')),
                ('scc_size_before', models.IntegerField(blank=True, null=True)),
                ('fan_in_before', models.FloatField(blank=True, null=True)),
                ('fan_out_before', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='proposed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='dependencies.analysisrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
