# Generated by Django 5.2.10 on 2026-01-10 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencies', '0003_analysisrun_refactoringproposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level', models.IntegerField(help_text='Lower numbers = lower layers (e.g., 0=infrastructure, 1=domain, 2=application)')),
                ('description', models.TextField(blank=True, default='')),
                ('pattern', models.CharField(blank=True, default='', help_text="Regex pattern to auto-assign projects (e.g., '^infra:.*')", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LayerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_assigned', models.BooleanField(default=False, help_text='True if assigned automatically via pattern matching')),
                ('assigned_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layer_assignment', to='dependencies.project')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dependencies.layerdefinition')),
            ],
            options={
                'ordering': ['layer__level', 'project__name'],
            },
        ),
        migrations.CreateModel(
            name='LayerViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_violations', to='dependencies.analysisrun')),
                ('source_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dependencies.layerdefinition')),
                ('source_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_violations', to='dependencies.project')),
                ('target_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dependencies.layerdefinition')),
                ('target_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_violations', to='dependencies.project')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_in', models.IntegerField(default=0, help_text='Number of incoming dependencies')),
                ('fan_out', models.IntegerField(default=0, help_text='Number of outgoing dependencies')),
                ('coupling_score', models.FloatField(default=0.0)),
                ('afferent_coupling', models.IntegerField(default=0, help_text='Ca - incoming dependencies')),
                ('efferent_coupling', models.IntegerField(default=0, help_text='Ce - outgoing dependencies')),
                ('instability', models.FloatField(default=0.0, help_text='I = Ce / (Ca + Ce), 0=stable, 1=unstable')),
                ('degree_centrality', models.FloatField(default=0.0)),
                ('betweenness_centrality', models.FloatField(default=0.0)),
                ('topological_order', models.IntegerField(blank=True, help_text='Position in topological ordering (if DAG)', null=True)),
                ('layer_depth', models.IntegerField(blank=True, help_text='Longest path from any root node', null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('analysis_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_metrics', to='dependencies.analysisrun')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dependencies.project')),
            ],
            options={
                'verbose_name_plural': 'Node metrics',
                'ordering': ['-instability', '-coupling_score'],
            },
        ),
    ]
