# Generated by Django 5.2.10 on 2026-01-10 14:50

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependencies', '0004_layerdefinition_layerassignment_layerviolation_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
