# Generated by Django 5.2.10 on 2026-01-11 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencies', '0005_project_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('shared', 'Shared'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('snapshot_data', models.JSONField(blank=True, help_text='Frozen state for sharing', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent vision for branching', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='dependencies.vision')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', help_text='Optional description or rationale')),
                ('statement_type', models.CharField(blank=True, choices=[('existence', 'Existence'), ('containment', 'Containment'), ('exclusion', 'Exclusion'), ('cardinality', 'Cardinality'), ('coverage', 'Coverage')], max_length=20, null=True)),
                ('natural_language', models.TextField(help_text='Human-readable statement with $$$ref$$$ tokens')),
                ('formal_expression', models.JSONField(blank=True, help_text='Machine-evaluable expression', null=True)),
                ('status', models.CharField(choices=[('informal', 'Informal'), ('semi_formal', 'Semi-Formal'), ('formal', 'Formal')], default='informal', max_length=20)),
                ('is_satisfied', models.BooleanField(help_text='null = not evaluated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='dependencies.vision')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('definition_type', models.CharField(choices=[('informal', 'Informal'), ('tag_expression', 'Tag Expression'), ('explicit_list', 'Explicit List'), ('layer', 'Layer')], default='informal', max_length=20)),
                ('tag_expression', models.JSONField(blank=True, help_text='e.g., {"and": ["payment", "api"]}', null=True)),
                ('explicit_members', models.JSONField(default=list, help_text='List of project keys')),
                ('layer_id', models.IntegerField(blank=True, help_text='ID of referenced layer (for layer definition type)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='dependencies.vision')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'vision')},
            },
        ),
    ]
