# Generated by Django 5.2.10 on 2026-01-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencies', '0006_add_coverage_statement_and_layer_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='statement_type',
            field=models.CharField(blank=True, choices=[('existence', 'Existence'), ('containment', 'Containment'), ('exclusion', 'Exclusion'), ('cardinality', 'Cardinality'), ('coverage', 'Coverage'), ('correspondence', 'Correspondence'), ('refinement', 'Refinement')], max_length=20, null=True),
        ),
    ]
