# Generated by Django 5.2.10 on 2026-01-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencies', '0007_alter_statement_statement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('stale', 'Stale'), ('dormant', 'Dormant'), ('not_analyzed', 'Not Analyzed'), ('orphan', 'Orphan')], default='active', max_length=20),
        ),
    ]
