# Generated by Django 5.2.10 on 2026-01-13 00:45

from django.db import migrations, models


def reset_status_to_not_analyzed(apps, schema_editor):
    """Set all existing projects to not_analyzed."""
    Project = apps.get_model('dependencies', 'Project')
    Project.objects.update(status='not_analyzed')


class Migration(migrations.Migration):

    dependencies = [
        ('dependencies', '0008_add_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('stale', 'Stale'), ('dormant', 'Dormant'), ('not_analyzed', 'Not Analyzed'), ('orphan', 'Orphan')], default='not_analyzed', max_length=20),
        ),
        migrations.RunPython(reset_status_to_not_analyzed, migrations.RunPython.noop),
    ]
