# Generated by Django 5.2.10 on 2026-01-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencies', '0009_change_status_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='internal',
            field=models.BooleanField(default=True, help_text='True for internal projects, False for external packages'),
        ),
    ]
