# Generated by Django 5.2.10 on 2026-01-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencies', '0010_add_project_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='basename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
