# Generated by Django 5.2.10 on 2026-01-13 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencies', '0011_add_project_basename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodegroup',
            options={'ordering': ['key']},
        ),
        migrations.AddField(
            model_name='nodegroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dependencies.nodegroup'),
        ),
    ]
