# Generated by Django 5.2.10 on 2026-01-12 18:58

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependencies', '0007_alter_statement_statement_type'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('include_active', models.BooleanField(default=True)),
                ('include_stale', models.BooleanField(default=True)),
                ('include_dormant', models.BooleanField(default=False)),
                ('include_never_analyzed', models.BooleanField(default=False)),
                ('include_orphan', models.BooleanField(default=False)),
                ('include_unused', models.BooleanField(default=True, help_text='Include projects with no dependents (leaf nodes)')),
                ('include_disconnected', models.BooleanField(default=True, help_text='Include projects not in the main cluster')),
                ('name_pattern', models.CharField(blank=True, default='', help_text='Filter by name pattern (supports * wildcard)', max_length=255)),
                ('active_days', models.IntegerField(default=30, help_text='Projects analyzed within this many days are "active"')),
                ('stale_days', models.IntegerField(default=90, help_text='Projects analyzed within this many days (but not active) are "stale"')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_default', models.BooleanField(default=False, help_text='Use this filter by default')),
                ('groups', models.ManyToManyField(blank=True, help_text='Only include projects in these groups (empty = all groups)', to='dependencies.nodegroup')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Only include projects with these tags (empty = ignore tags)', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
    ]
