# Generated by Django 5.2.10 on 2026-01-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scope', '0002_rename_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfilter',
            name='include_main_cluster',
            field=models.BooleanField(default=True, help_text='Include projects in the main connected cluster'),
        ),
        migrations.AlterField(
            model_name='projectfilter',
            name='include_disconnected',
            field=models.BooleanField(default=False, help_text='Include projects not in the main cluster'),
        ),
    ]
